version: '3.8'
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./src/frontend
    ports:
      - 8080:8080
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    env_file:
      - ./.env
    depends_on:
      - backend

  backend:
    build: ./src/backend
    ports:
      - 8090:8090
    working_dir: /app
    volumes:
      - ./src/backend:/app
    env_file:
      - ./.env
    environment:
      DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
